### ISSUE TITLE
Problem to use sift in Vlfeat

### ISSUE THREAD

**Issue by willard-yuan** [jesolem/PCV#14]
Hi, jesolem. In the `sift.py`:

``` python
    cmmd = str("sift.exe "+imagename+" --output="+resultname+
                " "+params)
    os.system(cmmd)
```

I have read you blog post [Another Python Interface for SIFT](http://www.janeriksolem.net/2011/06/another-python-interface-for-sift.html). You use the `os.system()` to call the vlfeat's `sift.exe` in the context the environment variable has been added to the system path. I did so, but it failed to dectect the sift key points.

Instead, I change it with a full path:

``` python
    cmmd = str("D:\\mltools\\vlfeat\\sift.exe "+imagename+" --output="+resultname+
                " "+params)
```

then it succeeds.

I don't know the reason why the former failed, can you help to let the former succeed?

**Comment by jesolem** [comment]
Did you add the full (absolute) path to the env variable?

**Comment by willard-yuan** [comment]
Yes, I do. I test it under **Windows 7** OS. After I add the full path to the env variable, It throws these error:

``` sh
Traceback (most recent call last):
  File "F:/dropbox/Dropbox/translation/pcv-notebook/ch02/ch02_sift.py", line 14, in <module>
    l1, d1 = sift.read_features_from_file('empire.sift')
  File "C:\Python27\lib\site-packages\PCV\localdescriptors\sift.py", line 30, in read_features_from_file
    f = loadtxt(filename)
  File "C:\Python27\lib\site-packages\numpy\lib\npyio.py", line 729, in loadtxt
processed tmp.pgm to empire.sift
    fh = iter(open(fname, 'U'))
IOError: [Errno 2] No such file or directory: 'empire.sift'
```

The error indicates it doesn't find the `sift.exe`. To solve this problem, I bulid a folder `.\\utils\\win32vlfeat\\sift.exe` to contains the `VLfeat`. It's [here](https://github.com/willard-yuan/pcv-book-code/blob/master/PCV/PCV/localdescriptors/sift.py). I don't think it's not a good way to solve this problem. Is there a perfect way to solve this problem?

**Comment by yc-kata** [comment]
It's a good way to this question， I think。

At 2014-08-12 08:31:59, "Yong Yuan" notifications@github.com wrote:

Yes, I do. I test it under Windows 7 OS. After I add the full path to the env variable, It throws these error:

Traceback (most recent call last):
  File "F:/dropbox/Dropbox/translation/pcv-notebook/ch02/ch02_sift.py", line 14, in <module>
    l1, d1= sift.read_features_from_file('empire.sift')
  File "C:\Python27\lib\site-packages\PCV\localdescriptors\sift.py", line 30, in read_features_from_file
    f= loadtxt(filename)
  File "C:\Python27\lib\site-packages\numpy\lib\npyio.py", line 729, in loadtxt
processed tmp.pgm to empire.sift
    fh= iter(open(fname, 'U'))
IOError: [Errno 2] No such file or directory: 'empire.sift'

The error indicates it doesn't find the sift.exe. To solve this problem, I bulid a folder .\utils\win32vlfeat\sift.exe to contains the VLfeat. It's here. I don't think it's not a good way to solve this problem. Is there a perfect way to solve this problem?

**Comment by willard-yuan** [comment]
It works, but not perfect. I hope to find a method which doesn't need to modify the source code `sift.py` of library `PCV`.

**Comment by jesolem** [comment]
People seem to have problems with the VLFeat executable. I'm going to try to replace that for the next edition. Thanks all.

**Comment by willard-yuan** [comment]
Great, I can't wait to read it.

**Comment by ngunhaSO** [comment]
@jesolem yes, I would love to read your next edition where you can replace the VLFeat executable by something less platform dependent. Thanks!
