### ISSUE TITLE
Python 3 compatibility?

### ISSUE THREAD

**Issue by recursive-duck** [jesolem/PCV#24]
I have installed PCV on Anaconda with python 3.5 and tried to compile this:

```
from PIL import Image
from pylab import *
from numpy import *

from PCV.localdescriptors import dsift, sift
```

basically dense sift example in examples. The compiler gives me the output:

Traceback (most recent call last):
  File "C:\Dropbox\Python\Sorusana\main.py", line 9, in <module>
    from PCV.localdescriptors import dsift, sift
  File "C:\Anaconda3\lib\site-packages\PCV\localdescriptors\dsift.py", line 38
    print 'processed', imagename, 'to', resultname
                    ^
SyntaxError: Missing parentheses in call to 'print'
[Finished in 1.5s]

I think it's because python 2 neture of the library. Any solutions?

**Comment by jesolem** [comment]
Yeah. The entire book and repository is using Python2. 

In you specific error you need to have parenthesis for print, like this
`print('processed', imagename, 'to', resultname)`

**Comment by subratajanaphd** [comment]
How to install PCV
 from PCV.classifiers import bayes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'PCV'

**Comment by uly94** [comment]
I have the same error...
"ModuleNotFoundError: No module named 'PCV'"
