### ISSUE TITLE
sift --edge-thresh 10 Error: unknown flag `edge-thresh'

### ISSUE THREAD

**Issue by manilal2** [jesolem/PCV#38]
Hello,

I downloaded shift and while executing (this is in reference  to book "programming computer Vision with python" by author Jan Erik Solem)

what I need to do to resolve this...?

-Thanks
-Alok 

python examples/ch3_panorama.py 
Error: unknown flag `edge-thresh'
processed tmp.pgm to ../data/Univ1.sift
Traceback (most recent call last):
  File "examples/ch3_panorama.py", line 24, in <module>
    l[i],d[i] = sift.read_features_from_file(featname[i])
  File "/Users/akmishra/Development/python2.7/lib/python2.7/site-packages/PCV/localdescriptors/sift.py", line 25, in read_features_from_file
    f = loadtxt(filename)
  File "/Users/akmishra/Development/python2.7/lib/python2.7/site-packages/numpy/lib/npyio.py", line 962, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/Users/akmishra/Development/python2.7/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 266, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/Users/akmishra/Development/python2.7/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 624, in open
    raise IOError("%s not found." % path)
IOError: ../data/Univ1.sift not found.

**Comment by manilal2** [comment]
I mean sift instead of shift
