### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by annyhou** [jesolem/PCV#43]
Traceback (most recent call last):
  File "imgsearch.py", line 32, in <module>
    res_reg = [w[1] for w in src.query(imlist[q_ind])[:nbr_results]] # 查询的结果 
  File "/opt/conda/lib/python3.8/site-packages/PCV/imagesearch/imagesearch.py", line 128, in query
    h = self.get_imhistogram(imname)
  File "/opt/conda/lib/python3.8/site-packages/PCV/imagesearch/imagesearch.py", line 96, in get_imhistogram
    return pickle.loads(str(s[0]))
TypeError: a bytes-like object is required, not 'str'

env: python3.8.8

**Comment by annyhou** [comment]
<img width="345" alt="image" src="https://user-images.githubusercontent.com/45547401/190996106-a964c3b6-d962-4594-bf6e-90c69437106b.png">

**Comment by annyhou** [comment]
TypeError: 'cmp' is an invalid keyword argument for sort()
